package io.tpan.chat.api.newchatlambda.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.time.Instant;
import java.util.List;
@DynamoDBTable(tableName = "Chats")
public class Chat {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String chatid;
    @DynamoDBAttribute
    private String chatTitle;
    @DynamoDBAttribute
    private String chatText;
    @DynamoDBAttribute
    private String chatType;
    @DynamoDBAttribute
    private Integer chatScore;
    @DynamoDBAttribute
    private String createdBy;
    @DynamoDBAttribute
    private Instant createdOn;
    @DynamoDBAttribute
    private List<ChatMessage> chatMessagesList;
    @DynamoDBAttribute
    private boolean deletedFlag;

    public String getChatTitle() {
        return chatTitle;
    }

    public void setChatTitle(String chatTitle) {
        this.chatTitle = chatTitle;
    }

    public String getChatText() {
        return chatText;
    }

    public void setChatText(String chatText) {
        this.chatText = chatText;
    }

    public String getChatType() {
        return chatType;
    }

    public void setChatType(String chatType) {
        this.chatType = chatType;
    }

    public Integer getChatScore() {
        return chatScore;
    }

    public void setChatScore(Integer chatScore) {
        this.chatScore = chatScore;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Instant getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Instant createdOn) {
        this.createdOn = createdOn;
    }

    public List<ChatMessage> getChatMessagesList() {
        return chatMessagesList;
    }

    public void setChatMessagesList(List<ChatMessage> chatMessagesList) {
        this.chatMessagesList = chatMessagesList;
    }

    public boolean isDeletedFlag() {
        return deletedFlag;
    }

    public void setDeletedFlag(boolean deletedFlag) {
        this.deletedFlag = deletedFlag;
    }

    public String getChatid() {
        return chatid;
    }

    public void setChatid(String chatid) {
        this.chatid = chatid;
    }
}
